version: "3.4"

services:
    application:
        build:
          context: .
          dockerfile: Simmakers.Test.ArtsiomLyshchyk/Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - database

    database:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: ${SA_PASSWORD}
            ACCEPT_EULA: ${ACCEPT_EULA}